services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${REPO}/api:${TAG}
        restart: unless-stopped
        tty: true
        ports:
            - ${HOME_PORT}:${HOME_PORT}
        env_file:
            - .env
            - docker/env
        dns:
            - 8.8.8.8
            - 8.8.4.4
        volumes:
            - /etc/localtime:/etc/localtime:ro # Set docker time
            - .:/var/www/home
        networks:
            - smm-network
# # Docker Network
networks:
    smm-network:
        driver: bridge
